CREATE TABLE `auto_table`  (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '用户名',
  `age` int NULL DEFAULT NULL COMMENT '年龄',
  `create_datetime` datetime NULL DEFAULT NULL COMMENT 'datetime格式时间',
  `update_timestamp` timestamp NULL DEFAULT NULL COMMENT 'timestamp格式时间',
  `birth_date` date NULL DEFAULT NULL COMMENT 'date格式时间',
  `start_time` time NULL DEFAULT NULL COMMENT 'time格式时间',
  `instant` datetime NULL DEFAULT NULL COMMENT 'instant格式时间',
  `date` datetime NULL DEFAULT NULL COMMENT 'localdatetime格式时间',
  `tinyint` tinyint NULL DEFAULT NULL COMMENT 'tinyint格式数据',
  `smallint` smallint NULL DEFAULT NULL COMMENT 'smallint格式数据',
  `mediumint` mediumint NULL DEFAULT NULL COMMENT 'mediumint格式数据',
  `float_val` float(10, 2) NULL DEFAULT NULL COMMENT 'float格式数据',
  `double_val` double(10, 2) NULL DEFAULT NULL COMMENT 'double格式数据',
  `decimal_val` decimal(10, 0) NULL DEFAULT NULL COMMENT 'decimal格式数据',
  `text` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT 'text格式文本',
  `longtext` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT 'longtext格式文本',
  `mediumtext` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT 'mediumtext格式文本',
  `tinytext` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT 'tinytext格式文本',
  `blob` blob NULL COMMENT 'blob格式数据',
  `char_val` char(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'char格式数据',
  `json` json NULL COMMENT 'json格式数据',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 7 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;
